name: grat_session_storage_manager
description: to fix error from html import on Android / IOS
version: 0.0.1
homepage: https://github.com/scriabinEtude/grat_session_storage_manager

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
